### ISSUE TITLE
Excuse me. Does it can run with ROS？

### ISSUE THREAD

**Issue by Bowen-Jiang** [fishmarch/Stereo-Plane-SLAM#1]
hello, thank you share the work.
i can run without ROS. 
But, I can not run with ROS,  
i try to add the ros_stereo of ORB SLAM 2.
it would be shot down and show the "Segmentation fault (core dumped)"  at 
src/Frame "double tt= std::chrono::duration_cast<std::chrono::duration<double> >(t2 - t1).count();"

**Comment by Bowen-Jiang** [comment]
你好, 感謝分享你的成果. 
我想使用ROS接收自己的相機數據, 嘗試使用ORB-SLAM2 Stereo ROS version, 是無法用ROS執行Stereo-Plane-SLAM,並會報錯"Segmentation fault (core dumped)"
請問可以提示如何修改嗎？謝謝抽空查看, 靜候佳音.

**Comment by fishmarch** [comment]
Hello. I did not try with ROS. Maybe you could just comment this line and try again, as this is just to compute the run-time.

**Comment by Bowen-Jiang** [comment]
Thank you for your Guidance!  i solved the problem.
