### ISSUE TITLE
Why can you add multiple vertices in PoseOptimization?

### ISSUE THREAD

**Issue by Epiphany-f** [fishmarch/Stereo-Plane-SLAM#2]
Hello ,In my opinion,there is only one vertices in PoseOptimization,because this function just optimizer pose.But in your code ,it can add a number of vertices? Can you explain it?

>
![Uploading 268_1714648563_hd.png…]()

**Comment by Epiphany-f** [comment]
![268_1714648563_hd](https://github.com/fishmarch/Stereo-Plane-SLAM/assets/58239558/930860a7-f35c-4565-9fdd-e03c62e83c70)

**Comment by fishmarch** [comment]
As in line 397, these vertexes are fixed.

**Comment by Epiphany-f** [comment]
I dn not know why fixed these vertexes?

**Comment by fishmarch** [comment]
Because only the pose is to be optimized.

**Comment by Epiphany-f** [comment]
But you actually add those vertexes,does that have any special meaning?

**Comment by fishmarch** [comment]
For simplicity.

**Comment by Epiphany-f** [comment]
OK,thanks,Are you Chinese?
